### ISSUE TITLE
Exercise 10: Email and URL Format Validation

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#10]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex10

The form you create like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png. Add validations for the correct format of email and homepage (url) using regular expressions. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
- Use proper convention.
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L20 - What does the `_` mean?
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L10 to https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L16 - Move this section into the constructor.
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L25 - Refactor the `hasValue()` method. Do the same in other exercises.
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L2 and https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L3 - You are to build the regex yourself. You can test it here https://regex101.com/#javascript.

**Comment by damilola-dealdey** [comment]
All Corrected.

**Comment by segunadeleye** [comment]
- There is a bug here https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L33. Always test your application properly before submitting it.
- There should be separate notifications for empty email field and invalid email. Same goes for the homepage URL. In other words, you should only check if the email or URL formats are valid if the fields are not empty.
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex10/validator.js#L96
  There is no need to assign the Validator object to a variable since you are not referencing it anywhere else.

**Comment by damilola-dealdey** [comment]
Done.

**Comment by segunadeleye** [comment]
Please attend to the feedback.

**Comment by damilola-dealdey** [comment]
Fixed

**Comment by segunadeleye** [comment]
Looks good
